# Generated by Django 4.1.2 on 2022-10-18 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('product_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('description', models.TextField()),
            ],
        ),
    ]
