# Generated by Django 4.1.2 on 2022-10-18 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000000000, verbose_name='Цена за единицу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Код продукта'),
        ),
    ]
