# Generated by Django 4.1.2 on 2023-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shopapp.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default='Тестовое описание товара', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
    ]
