# Generated by Django 4.1.2 on 2023-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_feedbackmodel_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-price'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Ваш телефонный номер'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='text',
            field=models.TextField(verbose_name='Ваше сообщение'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_in_cart', models.ManyToManyField(to='shopapp.products')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
