# Generated by Django 4.1.2 on 2023-02-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_ordermodel_remove_cartmodel_products_in_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='shopapp.cartmodel'),
            preserve_default=False,
        ),
    ]
