# Generated by Django 4.1.2 on 2023-02-07 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0009_userprofile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price_sum',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='покупатель'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='номер заказа'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='shopapp.products', verbose_name='номер заказа'),
        ),
    ]
