# Generated by Django 4.1.2 on 2023-02-07 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_remove_ordermodel_price_sum_ordermodel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='shopapp.products', verbose_name='Товары в заказе'),
        ),
    ]
